x-uffizzi:

  ingress:

    service: app

    port: 8080

services:

  app:

    build: .

    environment:

      NODE_ENV: staging
      ID : 4682685
      TOKEN : 5547113554:AAETQSL73_XfkcXN351sq1kT29qMe3_3Vw8
      HASH : 3eba5d471162181b8a3f7f5c0a23c307
     


    deploy:

      resources:

        limits:

          memory: 18000M

    restart: always

    ports:

      - "3000:3000"

    privileged: true

    depends_on:

      - app

    cap_add:

      - SYS_ADMIN

    restart: always

volumes:

  data:
